### ISSUE TITLE
Sub page order is not recorded unless parent field is has a value

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#263]
When i go to change the order of the sub pages in the menu, the parent value is blank be default.  when i change the order of the pages and submit, it is not saved.  i need to set the parent, submit again and then it is saved.  the parent value is not saved and when i enter the reorder page again the parent filed is blank.

This is a low priority bug.

prod/editorial/22/nodes/116/edit

**Comment by ltankey** [comment]
Thanks @nicholasgkdto we'll look into this - I've modified your message to remove the domain.

**Comment by tessereth** [comment]
This is related to SITES-386. I assume this is happening on a section home node. The parent gets prefilled as blank because the root node has no name. Then the form validation fails because the parent is required. If we don't show or validate the parent field for section home nodes, that should fix this bug.

**Comment by tessereth** [comment]
Fixed in v1.2.0
