### ISSUE TITLE
NameError: uninitialized constant CustomTemplateNodeForm

### ISSUE THREAD

**Issue by maxious** [AusDTO/gov-au-beta#294]
View details in Rollbar: [https://rollbar.com/ausdto/GOVAU_Beta_Prod/items/26/](https://rollbar.com/ausdto/GOVAU_Beta_Prod/items/26/)

```

NameError: uninitialized constant CustomTemplateNodeForm
...
  File "/home/vcap/app/app/helpers/editorial_helper.rb", line 4, in form_type
  File "/home/vcap/app/app/controllers/editorial/submissions_controller.rb", line 57, in find_node
 ...
```

**Comment by maxious** [comment]
This is the line of code https://github.com/AusDTO/gov-au-beta/blob/develop/app/helpers/editorial_helper.rb#L4

There isn't CustomTemplateNodeForm in https://github.com/AusDTO/gov-au-beta/tree/develop/app/forms

Maybe need to test for existance and fall back to default. Or if there does need to be one, should add a step to https://github.com/AusDTO/gov-au-beta/blob/develop/README.md#node-types to make a file

**Comment by ltankey** [comment]
This bug is caused by the absence of `CustomNodeTemplateForm` and the partial `submissions/_custom_node_template_form.html.haml`

This form type shouldn't allow the user to edit the content, as the content is contained within the template itself. Fields to change should be confined to `name` and `short_summary`

**Comment by ltankey** [comment]
Delivered in v0.9.0
